### ISSUE TITLE
JMH version upgrade?

### ISSUE THREAD

**Issue by akarnokd** [nebula-plugins/gradle-rxjava-project-plugin#16]
Are there any plans to upgrade to a more recent JMH version?

**Comment by quidryan** [comment]
jmh 1.0 is different enough that it could break people, right? I'd defer to @benjchristensen to what version he wants to use. You could try upping the versions yourself to see if it works well or not:

```
dependencies {
    perfCompile 'org.openjdk.jmh:jmh-core:1.0'
    perfCompile 'org.openjdk.jmh:jmh-generator-annprocess:1.0'
}
```
That would go after any apply plugin's.
```

**Comment by benjchristensen** [comment]
I thought we already were on 1.0. I'd like to get caught up and if we need to fix things we will.
