### ISSUE TITLE
Break out jmh/performance as a separate plugin?

### ISSUE THREAD

**Issue by mattrjacobs** [nebula-plugins/gradle-rxjava-project-plugin#17]
I would like to add perf tests to Hystrix (https://github.com/Netflix/Hystrix/issues/578).  Is there a way to add the jmh integration without all of the other rxjava-specific bits?

**Comment by quidryan** [comment]
You can always add the ReactiveX jar to your buildscript and then do `apply plugin: nebula.plugin.rxjavaproject.RxjavaPerformancePlugin`. 

You could look at the [jmh plugin for gradle](https://github.com/melix/jmh-gradle-plugin). It didn't exist when I did the ReactiveX plugin. I used it in [Skybar project](https://github.com/WinterTechForum/skybar/blob/master/skybar/build.gradle#L3) and it work ok.
