### ISSUE TITLE
Migrate to ReactiveX Org

### ISSUE THREAD

**Issue by benjchristensen** [nebula-plugins/gradle-rxjava-project-plugin#20]
Can we move this to the ReactiveX org? I recently cloned and modified this for ReactiveSocket and it is working well there: https://github.com/ReactiveSocket/gradle-nebula-plugin-reactivesocket

Since that worked, I think it would be cleaner to have this project live with ReactiveX since its only purpose is the ReactiveX Java projects. 

Any objections?

/cc @rspieldenner

**Comment by rspieldenner** [comment]
no objections. I will see it less often and may forget to update it when
I'm moving things to new gradle versions. So ping me if I do that.

**Comment by sghill** [comment]
@benjchristensen is this something you'd still be interested in?
