### ISSUE TITLE
Support Gradle 3.2.1

### ISSUE THREAD

**Issue by akarnokd** [nebula-plugins/gradle-rxjava-project-plugin#24]
I'm trying to switch RxJava 2.x from 2.14 over to 3.2.1 but this plugin (4.0.0) fails with the following error:

```
Caused by: java.lang.ClassNotFoundException: org.gradle.api.internal.project.AbstractProject
```

Do you have any tips or perhaps a plugin update?

**Comment by DanielThomas** [comment]
This plugin is Netflix internal - it's used as a project template for our ReactiveX projects for release management.

**Comment by jaredsburrows** [comment]
@DanielThomas This is still not fixed, do you have any plans to fix it?

**Comment by DanielThomas** [comment]
@jaredsburrows I'll do what I can to get the plugin compatible with Gradle 4.2.

That'll be the last work the Nebula team will do on this plugin however. The ReactiveX project should fork the plugin and maintain their project plugins from here on out. Of course, we'll still support any of the bundled Nebula plugins.

**Comment by akarnokd** [comment]
We rather don't want to use this bundle anymore. We didn't fork it before as there was nobody who understood Gradle on this level. Practically we only need bintray/maven release logic and the automatic version number generation logic.

**Comment by DanielThomas** [comment]
@akarnokd that would have been good to know before folks requested we fix this - I just spent a bunch of time getting this working.

**Comment by DanielThomas** [comment]
Well it's compatible with 4.2 except for the Android licensing issue w/ the tests - https://travis-ci.org/nebula-plugins/gradle-rxjava-project-plugin. I'll leave it there.

**Comment by akarnokd** [comment]
I never thought you'd do anything about this after my initial post 10 months ago.

**Comment by jaredsburrows** [comment]
@DanielThomas That link you posted says "this project is not active".
